on:
  release:
    types: [published]  # This triggers when a new release is published

permissions:
  contents: write

name: attach-release-assets

jobs:
  attach-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: 'true'
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install and Build OpenSCD
        run: |
          npm i @nx/nx-linux-x64-gnu
          npm clean-install
          npm run-script build
          npm run-script doc
      - name: Copy Core Docs to OpenSCD
        run: cp -R packages/core/doc packages/distribution/build/core-doc

      - name: Copy Plugin Docs to OpenSCD
        run: cp -R packages/oscd-official-plugins/doc packages/distribution/build/plugin-doc

      - name: Compress files
        run: tar -czf open-scd.tar.gz -C packages/distribution/build

      - name: Upload release files
        run: gh release upload ${{ steps.release.outputs.tag_name }} open-scd.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
