name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - "packages/**"

concurrency: preview-${{ github.ref }}
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install and Build OpenSCD
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
        run: |
          npm i @nx/nx-linux-x64-gnu
          npm clean-install
          PUBLIC_URL=open-scd/pr-preview/pr-$PR_NUMBER npm run-script build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: packages/distribution/build
          umbrella-dir: pr-preview
