name: Test and Build
on: pull_request

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install and build Core
        run: |
          cd packages/core
          npm clean-install
          npm run-script build

      - name: Install and Build OpenSCD
        run: |
          cd packages/open-scd
          npm clean-install
          npm run-script build

      - name: Install and Bundle Plugins
        run: |
          cd packages/plugins
          npm clean-install
          npm run-script test
          npm run-script bundle
